---
- hosts: ios
  gather_facts: yes
  connection: network_cli
  tasks:
   - name: Gather Local Facts
     setup:
     delegate_to: localhost 
   - name: Engine time
     debug: var=ansible_date_time.date
   - name: Gather Facts
     ios_facts:
       gather_subset:
        - "!hardware"
     register: config_response
   - name: Hostname for "{{ inventory_hostname }}"
     debug: var=ansible_net_hostname

   - name: Hostname for "{{ inventory_hostname }}"
     debug: var=ansible_net_config

   - name: Version for "{{ inventory_hostname }}"
     debug: var=ansible_net_version

   - name: CDP for "{{ inventory_hostname }}"
     debug: var=ansible_net_neighbors
   - name: Generate configuration files
     template:
       src: discovery.j2
       dest: ./git_remote/{{ inventory_hostname }}_report_{{ansible_date_time.date}}.yml
- name: Fully Sync changes into git_repo
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Fully Sync Changes into git_repo
      command: "{{ item }}"
      with_items:
       - pwd
       - git add .
       - git commit -m "Updates {{ansible_date_time.date}} {{ansible_date_time.time}}" -a
       - git push orign
      args:
       chdir: ./git_remote
